"""empty message

Revision ID: 53a80053bc30
Revises: 1315ffaca6de
Create Date: 2017-04-26 18:00:41.437516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a80053bc30'
down_revision = '1315ffaca6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ListOfWishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'Wishes', sa.Column('wishListID', sa.Integer(), nullable=False))
    op.drop_column(u'Wishes', 'userid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Wishes', sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column(u'Wishes', 'wishListID')
    op.drop_table('ListOfWishes')
    # ### end Alembic commands ###
