"""empty message

Revision ID: 6f7446d66f8a
Revises: 89d254681adc
Create Date: 2017-04-27 00:41:55.074525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7446d66f8a'
down_revision = '89d254681adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ListOfWishes')
    op.add_column('Wishes', sa.Column('userid', sa.Integer(), nullable=True))
    op.drop_column('Wishes', 'wishListID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Wishes', sa.Column('wishListID', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('Wishes', 'userid')
    op.create_table('ListOfWishes',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"ListOfWishes_id_seq"\'::regclass)'), nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'ListOfWishes_pkey')
    )
    # ### end Alembic commands ###
