"""empty message

Revision ID: 89d254681adc
Revises: 53a80053bc30
Create Date: 2017-04-27 00:27:01.758053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d254681adc'
down_revision = '53a80053bc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ListOfWishes', sa.Column('name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ListOfWishes', 'name')
    # ### end Alembic commands ###
